### ISSUE TITLE
How To Get The Cookies?

### ISSUE THREAD

**Issue by satriaadiper** [RozhBasXYZ/INSTAROZ#1]
![image](https://github.com/RozhBasXYZ/INSTAROZ/assets/67152028/b9be33fe-9182-43d4-9ad8-63600d419ce2)

**Comment by satriaadiper** [comment]
JUST USE F12. 
THEN SEARCH THE COOKIES

**Comment by RozhBasXYZ** [comment]
you must have an Instagram account as a victim, then you log in to the kiwi
application in the Play store there, download the cookiedogh extension then
get the cookie via the extension and enter the cookie into the script

Pada tanggal Sen, 24 Jul 2023 17.01, Satria Adi Permana <
***@***.***> menulis:
